import "dotenv/config";
const {
  MY_BOT_DISCORD_TOKEN,
  MY_BOT_APPLICATION_ID,
  ERROR_CHANNEL_ID,
  AUTHORIZATION,
  OPENAI_API_KEY,
  REPLICATE_API_KEY,
} = process.env;

if (
  !MY_BOT_DISCORD_TOKEN ||
  !MY_BOT_APPLICATION_ID ||
  !AUTHORIZATION ||
  !OPENAI_API_KEY ||
  !ERROR_CHANNEL_ID ||
  !REPLICATE_API_KEY
) {
  throw new Error(
    `Missing environment variables: 
    MY_BOT_DISCORD_TOKEN:${MY_BOT_DISCORD_TOKEN}, 
    MY_BOT_APPLICATION_ID:${MY_BOT_APPLICATION_ID}, 
    AUTHORIZATION: ${AUTHORIZATION},
    OPENAI_API_KEY: ${OPENAI_API_KEY},
    ERROR_CHANNEL_ID: ${ERROR_CHANNEL_ID}
    REPLICATE_API_KEY: ${REPLICATE_API_KEY}
    `
  );
}

const config: Record<string, string> = {
  MY_BOT_DISCORD_TOKEN,
  MY_BOT_APPLICATION_ID,
  AUTHORIZATION,
  OPENAI_API_KEY,
  ERROR_CHANNEL_ID,
  REPLICATE_API_KEY,
};

export default config;
